# Generated by Django 4.1.3 on 2022-12-05 12:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('blood', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=4)])),
                ('blood_type', models.CharField(choices=[('POSITIVE', 'positive'), ('NEGATIVE', 'negative')], default='POSITIVE', max_length=8)),
                ('cesarean', models.CharField(choices=[('NO', 'no cesarean'), ('ONE', 'one cesarean'), ('TWO', 'two cesarean'), ('THREE', 'three cesarean'), ('MORE', 'more')], default='NO', max_length=5)),
                ('children', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=5)])),
                ('is_public', models.BooleanField(default=False)),
                ('in_program', models.CharField(choices=[('NO', 'No program'), ('SUR', 'Surrogacy'), ('EGG', 'Egg donor')], default='NO', max_length=4)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
